### ISSUE TITLE
对于Mysql的操作

### ISSUE THREAD

**Issue by Helo-Man** [tencentyun/wafer-php-server-sdk#11]
请问一下，如果我想条件查询数据如查找30岁以下且为男性的人的信息改如果去写这个条件查询语句。
我尝试了DB::select("table",["*"],['age<"30"','sex="male"'],"and")但是不管用。

**Comment by Heartunder-Blade** [comment]
看了一下Mysql这个类的源码，感觉是不是写得太死了，只能获取相等的值，不能根据条件索引大于小于不等于的值。
