### ISSUE TITLE
Call to undefined method QCloud_WeApp_SDK\Auth\LoginService::getHttpHeader()

### ISSUE THREAD

**Issue by lyz7805** [tencentyun/wafer-php-server-sdk#12]
https://github.com/tencentyun/wafer-php-server-sdk/blob/03758c38ab3e0973ef646bd85ea3dae4d35021dc/lib/Auth/LoginService.php#L31

可直接修改为：
`$skey = Util::getHttpHeader(Constants::WX_HEADER_SKEY);`

**Comment by jas0ncn** [comment]
已修复。
https://github.com/tencentyun/wafer-php-server-sdk/commit/411ab2f68c716764b3e9711d23336d6e0603ed93
