### ISSUE TITLE
AuthApi.php中关于处理非代理方式请求session_key的问题

### ISSUE THREAD

**Issue by dengnianchen** [tencentyun/wafer-php-server-sdk#13]
使用非代理方式请求session_key时获取到的openid是错误的，一直是7200。

跟踪发现https://api.weixin.qq.com/sns/jscode2session 这个api的返回内容并不是只有session_key和openid两个字段，还会包含expire_time，而AuthApi.php的第22行

           `list($session_key, $openid) = array_values(self::getSessionKey($code));`

会把返回的expire_time赋值给$openid，所以就变成了7200。

**Comment by jas0ncn** [comment]
已修复：https://github.com/tencentyun/wafer-php-server-sdk/commit/e32d8877ae6324a791cb1282e8df57029f51ba64
