### ISSUE TITLE
如何使用MySQL 操作类进行模糊查询

### ISSUE THREAD

**Issue by hl9010** [tencentyun/wafer-php-server-sdk#15]
请问大神，MySQL 操作类，如何使用like和通配符进行模糊查询。

**Comment by jas0ncn** [comment]
https://github.com/tencentyun/wafer-php-server-sdk/blob/master/API.md#mysqlselecttablename-columns---conditions---operator--and-suffix--
参考例子中 “条件为字符串” 的情况：
```php
use  QCloud_WeApp_SDK\Mysql\Mysql as DB;

// 条件为字符串
$rows = DB::select('tableName', ['*'], 'nickname = "Jason"');
```
