### ISSUE TITLE
update sdk后登录失败

### ISSUE THREAD

**Issue by luojin** [tencentyun/wafer-php-server-sdk#6]
更新前，登录返回数据如下：
 
 "returnData": {
    "id":"abc",
    "skey":"abc",
    "user_info":{
"openId":"abv","nickName":"abv","gender":1,"language":"zh_CN","city":"Shenzhen","province":"Guangdong","country":"China","avatarUrl":"abv",
    "watermark":{"timestamp":1509190947,"appid":"abv"}},

    "duration":7200},
    "version":1,
    "componentName":"MA"}

---------------------------------------------------------------------------------------------------------

sdk更新后，登录返回数据如下：

    "returnData":{
    "user_info":{
    "openId":"abv",
    "nickName":"adds",
    "gender":1,"language":
    "zh_CN",
    "city":"Shenzhen",
 "province":"Guangdong","country":"China","avatarUrl":"add",
    "watermark":{"timestamp":1509190947,"appid":"dddd"}}},

    "version":1,
    "componentName":"MA"}

没有返回id和skey了。。。客户端处理的时候，又没更新，一直提示：
 var errorMessage = '登录请求没有包含会话响应，请确保服务器处理 `' + options.loginUrl + '` 的时候正确使用了 SDK 输出登录结果';

返回给客户端的result为：
data:""
errMsg:"request:ok"

求解答

**Comment by jas0ncn** [comment]
SDK 不要更新，2.0 搭配的是新版的小程序 SDK。
